<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WildOwl.Model\WildOwl.Model.csproj" />
    <ProjectReference Include="..\WildOwl.Repository\WildOwl.Repository.csproj" />
  </ItemGroup>

</Project>
